Update treehouse autoplay
matt-west/treehouse-autoplay pull request #2
Opened 2018-03-15 20:15 UTC by marcomilon

Hello matt,

I've done some work on your extension.

1) Update the code to make it work with the current version of teamtreehouse. When video ends it will play the next video.
2) Remove autoplay of current video. With the current version of teamtrehouse it's not needed.
3) Remove fullscreen feature because it's not working anymore.
4) Add run_at=document_start to make the extension starts as soon as possible.

2018-03-19 10:03 UTC, matt-west requested changes
Thanks @marcomilon! I appreciate you jumping in to update this.

I just have a couple minor comments. Can you please make those updates and then I’ll release the new version to the Chrome Web Store.

2018-03-19 10:03 UTC, matt-west commented on js/autoplay.js
> +	chrome.extension.sendMessage({active: "true"}, function(response) {
I think the response callback function is optional so we should be able to cut it here as it’s not doing anything. https://developer.chrome.com/apps/runtime#method-sendMessage

2018-03-19 10:03 UTC, matt-west commented on js/autoplay.js
> +		chrome.extension.sendMessage({active: "false"}, function(response) {
Same as my last comment about cutting the response callback.

2018-03-21 00:03 UTC, marcomilon commented
Hello matt, 

I've made the changes requested to the PR. :+1:

2018-03-21 09:14 UTC, matt-west approved these changes

2018-03-21 09:14 UTC, matt-west commented
Thanks @marcomilon!

2018-03-21 09:14 UTC, merged

2018-03-21 14:25 UTC, marcomilon commented
No problem.

2018-03-23 10:10 UTC, matt-west commented
I’ve released a new version of the extension to the Chrome Web Store.

2018-03-23 13:50 UTC, marcomilon commented
Great, good to know.

:)

On Fri, Mar 23, 2018 at 5:10 AM, Matt West <notifications@github.com> wrote:

> I’ve released a new version of the extension to the Chrome Web Store.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/matt-west/treehouse-autoplay/pull/2#issuecomment-375605196>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA07hQh_eAPGXb-oNqKHMO0gnhrZ7JFQks5thMowgaJpZM4Ss0Li>
> .
>